name: Generate Snake Game

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v2
      - name: Gerando animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: jeffersonnjunior
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Adicionando ao commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Gerando nova animação da cobrinha"
          git push
